import csv
from bs4 import BeautifulSoup

html = '''
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','AFG' )"><option value="" selected="selected"></option><option value="FAI">Fairbanks</option><option value="BRW">Utqiagvik (Barrow)</option><option value="OTZ">Kotzebue</option><option value="OME">Nome</option><option value="MCG">McGrath</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','AFC' )"><option value="" selected="selected"></option><option value="ANC">Anchorage</option><option value="BET">Bethel</option><option value="CDB">Cold Bay</option><option value="AKN">King Salmon</option><option value="ADQ">Kodiak</option><option value="MCG">McGrath</option><option value="SNP">Saint Paul</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','AJK' )"><option value="" selected="selected"></option><option value="AJN">Juneau</option><option value="YAK">Yakutat</option><option value="ASI">Sitka</option><option value="KTN">Ketchikan</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','SEW' )"><option value="" selected="selected"></option><option value="SEA">Seattle-Tacoma, WA</option><option value="OLM">Olympia, WA</option><option value="SEW">WFO Seattle, WA</option><option value="UIL">Quillayute Airport, WA</option><option value="BLI">Bellingham, WA</option><option value="HQM">Hoquiam, WA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','PQR' )"><option value="" selected="selected"></option><option value="AST">Astoria - KAST</option><option value="UAO">Aurora - KUAO</option><option value="EUG">Eugene - KEUG</option><option value="HIO">Hillsboro - KHIO</option><option value="MMV">McMinnville - KMMV</option><option value="PDX">Portland - KPDX</option><option value="RDM">Redmond - KRDM</option><option value="RBG">Roseburg - KRBG</option><option value="SLE">Salem - KSLE</option><option value="SPB">Scappoose - KSPB</option><option value="DLS">The Dalles - KDLS</option><option value="TTD">Troutdale - KTTD</option><option value="VUO">Vancouver - KVUO</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','OTX' )"><option value="" selected="selected"></option><option value="GEG">Spokane, WA</option><option value="SFF">Felts Field, WA</option><option value="DEW">Deer Park, WA</option><option value="PUW">Pullman, WA</option><option value="LWS">Lewiston, ID</option><option value="MWH">Moses Lake, WA</option><option value="EPH">Ephrata, WA</option><option value="EAT">Wenatchee, WA</option><option value="OMK">Omak, WA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','PDT' )"><option value="" selected="selected"></option><option value="PDT">Pendleton, Oregon</option><option value="MEH">Meacham, Oregon</option><option value="RDM">Redmond, Oregon</option><option value="DLS">Dallesport, Washington</option><option value="ELN">Ellensburg, Washington</option><option value="PSC">Pasco, Washington</option><option value="YKM">Yakima, Washington</option><option value="ALW">Walla Walla, Washington</option><option value="HRI">Hermiston, Oregon</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MSO' )"><option value="" selected="selected"></option><option value="MSO">Missoula, MT</option><option value="GPI">Kalispell, MT</option><option value="BTM">Butte, MT</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BOI' )"><option value="" selected="selected"></option><option value="BOI">Boise, ID</option><option value="BKE">Baker City, OR</option><option value="BNO">Burns, OR</option><option value="JER">Jerome, ID</option><option value="MYL">McCall, ID</option><option value="MUO">Mountain Home, ID</option><option value="ONO">Ontario, OR</option><option value="REO">Rome, OR</option><option value="TWF">Twin Falls, ID</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','TFX' )"><option value="" selected="selected"></option><option value="BZN">Bozeman, MT</option><option value="CTB">Cut Bank, MT</option><option value="DLN">Dillon, MT</option><option value="GTF">Great Falls, MT</option><option value="HVR">Havre, MT</option><option value="HLN">Helena, MT</option><option value="LWT">Lewistown, MT</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','GGW' )"><option value="" selected="selected"></option><option value="GGW">Glasgow, Montana</option><option value="JDN">Jordan, MT</option><option value="OLF">Wolf Point, MT</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','PIH' )"><option value="" selected="selected"></option><option value="BYI">Burley, ID</option><option value="LLJ">Challis, ID</option><option value="IDA">Idaho Falls, ID</option><option value="PIH">Pocatello, ID</option><option value="RXE">Rexburg, ID</option><option value="SNT">Stanley, ID</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','STO' )"><option value="" selected="selected"></option><option value="Blu">Blue Canyon, CA</option><option value="STO">Downtown Sacramento, CA</option><option value="MYV">Marysville, CA</option><option value="MOD">Modesto, CA</option><option value="OVE">Oroville, CA</option><option value="RDD">Redding, CA</option><option value="RBL">Red Bluff, CA</option><option value="SAC">Sacramento Executive Airport, CA</option><option value="SMF">Sacramento International Airport, CA</option><option value="SCK">Stockton, CA</option><option value="VCB">Vacaville, CA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','EKA' )"><option value="" selected="selected"></option><option value="ACV">Arcata, CA</option><option value="CEC">Crescent City, CA</option><option value="EKA">Eureka, CA</option><option value="UKI">Ukiah, CA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MTR' )"><option value="" selected="selected"></option><option value="STS">Santa Rosa Airport</option><option value="APC">Napa Airport</option><option value="SFD">Downtown San Francisco</option><option value="SFO">San Francisco Airport</option><option value="OAK">Oakland Airport</option><option value="CCR">Concord Airport</option><option value="LVK">Livermore Airport</option><option value="HWD">Hayward Airport</option><option value="SJC">San Jose</option><option value="WVI">Watsonville Airport</option><option value="MRY">Monterey Airport</option><option value="SNS">Salinas Airport</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LOX' )"><option value="" selected="selected"></option><option value="BUR">Burbank, CA</option><option value="CMA">Camarillo, CA</option><option value="HHR">Hawthorne, CA</option><option value="WJF">Lancaster, CA</option><option value="LAX">Los Angeles Airport, CA</option><option value="CQT">Los Angeles Downtown, CA</option><option value="LGB">Long Beach, CA</option><option value="OXR">Oxnard Airport, CA</option><option value="PMD">Palmdale, CA</option><option value="PRB">Paso Robles, CA</option><option value="SBP">San Luis Obispo, CA</option><option value="SBA">Santa Barbara, CA</option><option value="SMX">Santa Maria, CA</option><option value="SMO">Santa Monica, CA</option><option value="SDB">Sandberg, CA</option><option value="VNY">Van Nuys, CA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MFR' )"><option value="" selected="selected"></option><option value="AAT">Alturas, CA</option><option value="LMT">Klamath Falls, OR</option><option value="MFR">Medford, OR</option><option value="SIY">Montague, CA</option><option value="MHS">Mount Shasta, CA</option><option value="OTH">North Bend, OR</option><option value="RBG">Roseburg, OR</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','REV' )"><option value="" selected="selected"></option><option value="RNO">Reno, NV</option><option value="TVL">South Lake Tahoe, CA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','HNX' )"><option value="" selected="selected"></option><option value="FAT">Fresno, California</option><option value="BFL">Bakersfield, California</option><option value="MCE">Merced, California</option><option value="MAE">Madera, California</option><option value="HJO">Hanford, California</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','SGX' )"><option value="" selected="selected"></option><option value="CRQ">Carlsbad, CA</option><option value="CNO">Chino Airport, CA</option><option value="FUL">Fullerton, CA</option><option value="SNA">John Wayne Airport, CA</option><option value="OKB">Oceanside Airport, CA</option><option value="ONT">Ontario, CA</option><option value="PSP">Palm Springs, CA</option><option value="RAL">Riverside, CA</option><option value="RIV">Riverside March ARB, CA</option><option value="RNM">Ramona, CA</option><option value="SAN">San Diego Intl, CA</option><option value="SDM">San Diego Brown Field, CA</option><option value="MYF">San Diego Mont. Field, CA</option><option value="TRM">Thermal, CA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LKN' )"><option value="" selected="selected"></option><option value="EKO">Elko Airport</option><option value="ELY">Ely Airport</option><option value="P68">Eureka Airport</option><option value="TPH">Tonopah Airport</option><option value="WMC">Winnemucca Airport</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','VEF' )"><option value="" selected="selected"></option><option value="LAS">Las Vegas, NV</option><option value="VGT">North Las Vegas, NV</option><option value="DRA">Desert Rock-Mercury, NV</option><option value="IGM">Kingman, AZ</option><option value="DAG">Barstow-Daggett, CA</option><option value="EED">Needles, CA</option><option value="BIH">Bishop, CA</option><option value="DVF">Death Valley, CA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','PSR' )"><option value="" selected="selected"></option><option value="PHX">Phoenix</option><option value="NYL">Yuma</option><option value="IPL">El Centro</option><option value="DVT">Deer Valley</option><option value="SDL">Scottsdale</option><option value="FFZ">Mesa</option><option value="BLH">Blythe</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','SLC' )"><option value="" selected="selected"></option><option value="EVW">Evanston, Wyoming</option><option value="CDC">Cedar City, UT</option><option value="SLC">Salt Lake City, UT</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','RIW' )"><option value="" selected="selected"></option><option value="BPI">Big Piney, WY</option><option value="BYG">Buffalo, WY</option><option value="CPR">Casper, WY</option><option value="COD">Cody, WY</option><option value="GEY">Greybull, WY</option><option value="JAC">Jackson, WY</option><option value="P60">Lake Yellowstone, WY</option><option value="LND">Lander, WY</option><option value="RIW">Riverton, WY</option><option value="RKS">Rock Springs, WY</option><option value="WRL">Worland, WY</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BYZ' )"><option value="" selected="selected"></option><option value="BIL">Billings</option><option value="MLS">Miles City</option><option value="LVM">Livingston</option><option value="SHR">Sheridan</option><option value="BHK">Baker</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','FGZ' )"><option value="" selected="selected"></option><option value="FLG">Flagstaff, AZ</option><option value="PRC">Prescott, AZ</option><option value="INW">Winslow, AZ</option><option value="GCN">Grand Canyon Airport, AZ</option><option value="PGA">Page, AZ</option><option value="SJN">Saint Johns, AZ</option><option value="RQE">Window Rock, AZ</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','TWC' )"><option value="" selected="selected"></option><option value="TUS">Tucson, AZ</option><option value="OLS">Nogales, AZ</option><option value="SAD">Safford, AZ</option><option value="DUG">Douglas, AZ</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','EPZ' )"><option value="" selected="selected"></option><option value="ELP">El Paso, TX</option><option value="DMN">Deming, NM</option><option value="TCS">Truth or Consequences, NM</option><option value="SVC">Silver City, NM</option><option value="SRR">Ruidoso, NM</option><option value="ALM">Alamogordo, NM</option><option value="LRU">Las Cruces, NM</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','ABQ' )"><option value="" selected="selected"></option><option value="ABQ">Albuquerque, New Mexico</option><option value="CAO">Clayton, New Mexico</option><option value="FMN">Farmington, New Mexico</option><option value="GUP">Gallup, New Mexico</option><option value="LVS">Las Vegas, New Mexico</option><option value="RTN">Raton, New Mexico</option><option value="ROW">Roswell, New Mexico</option><option value="SAF">Santa Fe, New Mexico</option><option value="TCC">Tucumcari, New Mexico</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','AMA' )"><option value="" selected="selected"></option><option value="AMA">Amarillo, TX</option><option value="BGD">Borger, TX</option><option value="DHT">Dalhart, TX</option><option value="GUY">Guymon, OK</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LUB' )"><option value="" selected="selected"></option><option value="LBB">Lubbock International Airport</option><option value="CDS">Childress Airport</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MAF' )"><option value="" selected="selected"></option><option value="E38">Alpine, TX</option><option value="E11">Andrews, TX</option><option value="ATS">Artesia, NM</option><option value="E41">Big Lake, TX</option><option value="BPG">Big Spring, TX</option><option value="CNM">Carlsbad, NM</option><option value="6R6">Dryden, TX</option><option value="FST">Fort Stockton, TX</option><option value="GDP">Guadalupe Pass, TX</option><option value="HOB">Hobbs, NM</option><option value="T89">Lajitas, TX</option><option value="LUV">Lamesa, TX</option><option value="MRF">Marfa, TX</option><option value="MDD">Midland Airpark, TX</option><option value="MAF">Midland International Airport, TX</option><option value="MRF">Marfa, TX</option><option value="ODO">Odessa, TX</option><option value="PEQ">Pecos, TX</option><option value="PRS">Presidio, TX</option><option value="GNC">Seminole, TX</option><option value="SNK">Snyder, TX</option><option value="VHN">Van Horn, TX</option><option value="INK">Wink, TX</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','SJT' )"><option value="" selected="selected"></option><option value="ABI">Abilene, TX</option><option value="SJT">San Angelo, TX</option><option value="JCT">Junction, TX</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','EWX' )"><option value="" selected="selected"></option><option value="AUS">Austin Bergstrom</option><option value="ATT">Austin Mabry</option><option value="DRT">Del Rio</option><option value="SAT">San Antonio</option><option value="5C1">Boerne</option><option value="BMQ">Burnet</option><option value="CZT">Carizzo Springs</option><option value="5T9">Eagle Pass</option><option value="T82">Fredericksburg</option><option value="GTU">Georgetown</option><option value="GYB">Giddings</option><option value="T20">Gonzales</option><option value="HDO">Hondo</option><option value="DZB">Horseshoe Bay</option><option value="2R9">Kenedy</option><option value="ERV">Kerrville</option><option value="RYW">Lago Vista</option><option value="3T5">La Grange</option><option value="DLF">Laughlin AFB</option><option value="AQO">Llano</option><option value="BAZ">New Braunfels</option><option value="EDC">Pflugerville</option><option value="PEZ">Pleasanton</option><option value="RND">Randolph AFB</option><option value="ECU">Rocksprings</option><option value="SKF">San Antonio Kelly</option><option value="SSF">San Antonio Stinson</option><option value="HYI">San Marcos</option><option value="SEQ">Seguin</option><option value="T74">Taylor</option><option value="UVA">Uvalde</option><option value="CVB">Castroville</option><option value="FTN">Faith Ranch</option><option value="T70">Spofford</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','CRP' )"><option value="" selected="selected"></option><option value="CRP">Corpus Christi, TX</option><option value="VCT">Victoria, TX</option><option value="LRD">Laredo, TX</option><option value="COT">Cotulla, TX</option><option value="ALI">Alice, TX</option><option value="RKP">Rockport, TX</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BRO' )"><option value="" selected="selected"></option><option value="MFE">McAllen, Texas</option><option value="HRL">Harlingen, Texas</option><option value="PIL">Bayview/Port Isabel, Texas</option><option value="BRO">Brownsville, Texas</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','HGX' )"><option value="" selected="selected"></option><option value="IAH">Houston-Intercontinental, TX</option><option value="HOU">Houston-Hobby, TX</option><option value="GLS">Galveston, TX</option><option value="CLL">College Station, TX</option><option value="CXO">Conroe, TX</option><option value="DWH">DW Hooks, TX</option><option value="LBX">Angleton, TX</option><option value="LVJ">Pearland, TX</option><option value="PSX">Palacios, TX</option><option value="SGR">Sugar Land, TX</option><option value="UTS">Hunstville, TX</option><option value="HGX">League City, TX</option><option value="ARM">Wharton, TX</option><option value="11R">Brenham, TX</option><option value="BYY">Bay City, TX</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','FWD' )"><option value="" selected="selected"></option><option value="DFW">Dallas/Fort Worth, TX</option><option value="ACT">Waco, TX</option><option value="DAL">Dallas Love Field, TX</option><option value="GKY">Arlington, TX</option><option value="F44">Athens, TX</option><option value="0F2">Bowie, TX</option><option value="XBP">Bridgeport, TX</option><option value="T35">Cameron, TX</option><option value="CPT">Cleburne, TX</option><option value="MKN">Comanche, TX</option><option value="CRS">Corsicana, TX</option><option value="RBD">Dallas Executive, TX</option><option value="LUD">Decatur, TX</option><option value="DTO">Denton, TX</option><option value="FTW">Fort Worth Meacham, TX</option><option value="AFW">Fort Worth Alliance, TX</option><option value="GLE">Gainesville, TX</option><option value="GOP">Gatesville, TX</option><option value="RPH">Graham, TX</option><option value="GDJ">Granbury, TX</option><option value="GVT">Greenville, TX</option><option value="LHB">Hearne, TX</option><option value="INJ">Hillsboro, TX</option><option value="ILE">Killeen Skylark, TX</option><option value="TKI">McKinney, TX</option><option value="MWL">Mineral Wells, TX</option><option value="PSN">Palestine, TX</option><option value="PRX">Paris, TX</option><option value="F46">Rockwall, TX</option><option value="GYI">Sherman/Denison, TX</option><option value="SEP">Stephenville, TX</option><option value="TPL">Temple, TX</option><option value="TRL">Terrell, TX</option><option value="PWG">Waco McGregor, TX</option><option value="JWY">Waxahachie, TX</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','OUN' )"><option value="" selected="selected"></option><option value="OKC">Oklahoma City Will Rogers Airport</option><option value="SPS">Wichita Falls Airport/Sheppard AFB</option><option value="CSM">Clinton-Sherman Airport</option><option value="FDR">Frederick Municipal Airport</option><option value="GAG">Gage Airport</option><option value="GOK">Guthrie Municipal Airport</option><option value="HBR">Hobart Municipal Airport</option><option value="LAW">Lawton-Fort Sill Regional Airport</option><option value="PNC">Ponca City Regional Airport</option><option value="SWO">Stillwater Regional Airport</option><option value="PWA">Wiley Post Airport</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','SHV' )"><option value="" selected="selected"></option><option value="SHV">Shreveport, Louisiana</option><option value="MLU">Monroe, Louisiana</option><option value="TXK">Texarkana, Arkansas</option><option value="ELD">El Dorado, Arkansas</option><option value="DEQ">DeQueen, Arkansas</option><option value="TYR">Tyler, Texas</option><option value="GGG">Longview, Texas</option><option value="LFK">Lufkin, Texas</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LCH' )"><option value="" selected="selected"></option><option value="LCH">Lake Charles, LA</option><option value="AEX">Alexandria, LA</option><option value="ARA">New Iberia, LA</option><option value="BPT">Beaumont/Port Arthur, TX</option><option value="LFT">Lafayette, LA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','TSA' )"><option value="" selected="selected"></option><option value="TUL">Tulsa OK International Airport</option><option value="FSM">Fort Smith AR Regional Airport</option><option value="BVO">Bartlesville OK Municipal Airport</option><option value="FYV">Fayetteville AR Drake Field</option><option value="RVS">Jenks OK Riverside Airport</option><option value="MLC">McAlester OK Regional Airport</option><option value="MKO">Muskogee OK Davis Field</option><option value="XNA">Northwest AR Regional Airport</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LZK' )"><option value="" selected="selected"></option><option value="LIT">Little Rock, AR</option><option value="LZK">North Little Rock, AR</option><option value="LRF">Jacksonville/Little Rock AFB, AR</option><option value="HRO">Harrison, AR</option><option value="PBF">Pine Bluff, AR</option><option value="LLQ">Monticello, AR</option><option value="BPK">Mountain Home Airport, AR</option><option value="SRC">Searcy Municipal Airport, AR</option><option value="RUE">Russellville, AR</option><option value="MWT">Mount Ida, AR</option><option value="HOT">Hot Springs Memorial Field, AR</option><option value="FLP">Flippin/Marion County Regional Airport, AR</option><option value="SGT">Stuttgart Municipal Airport</option><option value="BVX">Batesville Regional Airport</option><option value="ADF">Arkadelphia Dexter Florence Airport, AR</option><option value="MEZ">Mena Intermountain Municipal Airport, AR</option><option value="CCA">Clinton Municipal Airport, AR</option><option value="CXW">Conway Cantrell Field, AR</option><option value="ARG">Walnut Ridge, AR</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LIX' )"><option value="" selected="selected"></option><option value="BTR">Baton Rouge, LA</option><option value="MSY">New Orleans, LA</option><option value="GPT">Gulfport, MS</option><option value="MCB">McComb, MS</option><option value="NEW">New Orleans Lakefront, LA</option><option value="PQL">Pascagoula, MS</option><option value="ASD">Slidell, LA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','JAN' )"><option value="" selected="selected"></option><option value="GLH">Greenville, MS</option><option value="GWO">Greenwood, MS</option><option value="HBG">Hattiesburg, MS</option><option value="HKS">Jackson, MS (Hawkins Field)</option><option value="JAN">Jackson, MS (Intl Airport)</option><option value="MEI">Meridian, MS</option><option value="TVR">Tallulah/Vicksburg</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MEG' )"><option value="" selected="selected"></option><option value="MEM">Memphis Intl Apt, TN</option><option value="MKL">Jackson, TN</option><option value="JBR">Jonesboro, AR</option><option value="TUP">Tupelo, MS</option><option value="MEG">WFO Memphis, TN</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MOB' )"><option value="" selected="selected"></option><option value="MOB">Mobile Regional Airport</option><option value="PNS">Pensacola International Airport</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BMX' )"><option value="" selected="selected"></option><option value="ANB">Anniston, AL</option><option value="AUO">Auburn, AL</option><option value="BHM">Birmingham, AL</option><option value="EET">Calera, AL</option><option value="MGM">Montgomery, AL</option><option value="TCL">Tuscaloosa, AL</option><option value="TOI">Troy, AL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','HUN' )"><option value="" selected="selected"></option><option value="HSV">Huntsville, AL</option><option value="MSL">Muscle Shoals, AL</option><option value="DCU">Decatur, AL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','OHX' )"><option value="" selected="selected"></option><option value="CKV">Clarksville, TN</option><option value="CSV">Crossville, TN</option><option value="BNA">Nashville, TN</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','HFO' )"><option value="" selected="selected"></option><option value="HNL">Honolulu, HI</option><option value="ITO">Hilo, HI</option><option value="OGG">Kahului, HI</option><option value="KOA">Kailua-Kona, HI</option><option value="JRF">Kalaeloa, HI</option><option value="NGF">Kaneohe, HI</option><option value="LIH">Lihue, HI</option><option value="MKK">Molokai, HI</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','KEY' )"><option value="" selected="selected"></option><option value="EYW">Key West, Florida</option><option value="MTH">Marathon, Florida</option><option value="KEY">WFO Key West, Florida</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MFL' )"><option value="" selected="selected"></option><option value="MIA">Miami, FL</option><option value="FLL">Fort Lauderdale, FL</option><option value="PBI">West Palm Beach, FL</option><option value="APF">Naples, FL</option><option value="TMB">Kendall-Tamiami, FL</option><option value="OPF">Opa Locka, FL</option><option value="FXE">North Fort Lauderdale, FL</option><option value="HWO">Pembroke Pines, FL</option><option value="PMP">Pompano Beach, FL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MLB' )"><option value="" selected="selected"></option><option value="DAB">Daytona Beach, FL</option><option value="MCO">Orlando International, FL</option><option value="MLB">Melbourne, FL</option><option value="VRB">Vero Beach, FL</option><option value="ORL">Orlando Executive, FL</option><option value="SFB">Sanford, FL</option><option value="FPR">Fort Pierce, FL</option><option value="LEE">Leesburg, FL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','TBW' )"><option value="" selected="selected"></option><option value="TPA">Tampa, FL</option><option value="LAL">Lakeland, FL</option><option value="SRQ">Sarasota-Bradenton, FL</option><option value="FMY">Fort Myers - Page Field, FL</option><option value="BKV">Brooksville, FL</option><option value="PIE">St. Petersburg-Clearwater, FL</option><option value="SPG">St. Petersburg - Albert Whitted, FL</option><option value="GIF">Winter Haven, FL</option><option value="PGD">Punta Gorda, FL</option><option value="RSW">Fort Myers - SW Int'l, FL</option><option value="TBW">NWS Ruskin, FL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','TAE' )"><option value="" selected="selected"></option><option value="TLH">Tallahassee Intl. Airport, Florida</option><option value="AAF">Apalachicola, Florida</option><option value="ECP">Northwest Florida Beaches Intl. Airport, Florida</option><option value="MAI">Marianna, Florida</option><option value="DHN">Dothan Airport, Alabama</option><option value="ABY">Albany, Georgia</option><option value="VLD">Valdosta, Georgia</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','JAX' )"><option value="" selected="selected"></option><option value="JAX">Jacksonville Intl Airport</option><option value="CRG">Craig Exec Airport</option><option value="SSI">St. Simons Island Airport</option><option value="GNV">Gainesville Regional Airport</option><option value="GNV">Alma - Bacon County Airport</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','FFC' )"><option value="" selected="selected"></option><option value="ATL">Atlanta, GA</option><option value="AHN">Athens, GA</option><option value="CSG">Columbus, GA</option><option value="MCN">Macon, GA</option><option value="VPC">Cartersville, GA</option><option value="PDK">DeKalb Peachtree Airport, GA</option><option value="FTY">Fulton County Airport, GA</option><option value="GVL">Gainesville, GA</option><option value="FFC">Peachtree City, GA</option><option value="RMG">Rome, GA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BOU' )"><option value="" selected="selected"></option><option value="DEN">Denver, CO</option><option value="AKO">Akron, CO</option><option value="APA">Centennial, CO</option><option value="LIC">Limon, CO</option><option value="GXY">Greeley Airport, CO</option><option value="FNL">Northern Colorado Regional, CO</option><option value="BDU">Boulder, CO</option><option value="33V">Walden, CO</option><option value="20V">Kremmling Airport, CO</option><option value="CCU">Copper Mountain, CO</option><option value="MNH">Monument Hill, CO</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','GJT' )"><option value="" selected="selected"></option><option value="GJT">Grand Junction, CO</option><option value="RIL">Rifle</option><option value="MTJ">Montrose</option><option value="DRO">Durango (airport)</option><option value="CEZ">Cortez</option><option value="CAG">Craig</option><option value="EEO">Meeker</option><option value="ASE">Aspen</option><option value="CNY">Moab, UT (airport)</option><option value="VEL">Vernal, UT</option><option value="DEN">Denver</option><option value="SLC">Salt Lake City</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','PUB' )"><option value="" selected="selected"></option><option value="ALS">Alamosa, CO</option><option value="COS">Colorado Springs, CO</option><option value="PUB">Pueblo, CO</option><option value="LHX">La Junta, CO</option><option value="LAA">Lamar, CO</option><option value="LXV">Leadville, CO</option><option value="SPD">Springfield, CO</option><option value="TAD">Trinidad, CO</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','GLD' )"><option value="" selected="selected"></option><option value="ITR">Burlington, CO</option><option value="GLD">Goodland, KS</option><option value="HLC">Hill City, KS</option><option value="MCK">McCook, NE</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','DDC' )"><option value="" selected="selected"></option><option value="DDC">Dodge City, KS</option><option value="GCK">Garden City, KS</option><option value="P28">Medicine Lodge, KS</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','UNR' )"><option value="" selected="selected"></option><option value="RAP">Rapid City Airport, SD</option><option value="UNR">Rapid City NWS, SD</option><option value="2WX">Buffalo, SD</option><option value="CUT">Custer, SD</option><option value="D07">Faith, SD</option><option value="PHP">Philip, SD</option><option value="IEN">Pine Ridge, SD</option><option value="ICR">Winner, SD</option><option value="GCC">Gillette, WY</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','ABR' )"><option value="" selected="selected"></option><option value="ABR">Aberdeen WFO</option><option value="PIR">Pierre</option><option value="ATY">Watertown</option><option value="MBG">Mobridge</option><option value="8D3">Sisseton</option><option value="FSD">Sioux Falls</option><option value="UNR">Rapid City</option><option value="RAP">Rapid City Airport</option><option value="HON">Huron Airport</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BIS' )"><option value="" selected="selected"></option><option value="BIS">Bismarck, ND</option><option value="XWA">Williston, ND</option><option value="DIK">Dickinson, ND</option><option value="JMS">Jamestown, ND</option><option value="MOT">Minot, ND</option><option value="N60">Garrison, ND</option><option value="HEI">Hettinger, ND</option></select>
'''

#BROKEN FOR SOME REASON
html2='''
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','FGF' )"><option value="" selected="selected"></option><option value="GFK">Grand Forks, ND</option><option value="FAR">Fargo, ND</option><option value="FGF">Grand Forks UND/WFO, ND</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CLI','CYS' )"><option value="" selected="selected"></option><option value="AIA">Alliance, NE</option><option value="CDR">Chadron, NE</option><option value="CYS">Cheyenne, WY</option><option value="DGW">Douglas, WY</option><option value="LAR">Laramie, WY</option><option value="RWL">Rawlins, WY</option><option value="BFF">Scottsbluff, NE</option><option value="SNY">Sidney, NE</option><option value="TOR">Torrington, WY</option></select>
'''

html3='''
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LBF' )"><option value="" selected="selected"></option><option value="BBW">Broken Bow, NE</option><option value="IML">Imperial, NE</option><option value="LBF">North Platte, NE</option><option value="VTN">Valentine, NE</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','GID' )"><option value="" selected="selected"></option><option value="AUH">Aurora, NE</option><option value="GRI">Grand Island, NE</option><option value="HSI">Hastings, NE</option><option value="HJH">Hebron, NE</option><option value="HDE">Holdrege, NE</option><option value="EAR">Kearney, NE</option><option value="LXN">Lexington, NE</option><option value="ODX">Ord, NE</option><option value="JYR">York, NE</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','ICT' )"><option value="" selected="selected"></option><option value="ICT">Wichita, KS</option><option value="SLN">Salina, KS</option><option value="CNU">Chanute, KS</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','TOP' )"><option value="" selected="selected"></option><option value="TOP">Topeka, KS</option><option value="CNK">Concordia, KS</option><option value="MHK">Manhattan, KS</option><option value="LWC">Lawrence, KS</option><option value="EMP">Emporia, KS</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','OAX' )"><option value="" selected="selected"></option><option value="OMA">Omaha, NE</option><option value="LNK">Lincoln, NE</option><option value="OFK">Norfolk, NE</option><option value="OAX">NWS Valley, NE</option><option value="TQE">Tekamah, NE</option><option value="FNB">Falls City, NE</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','FSD' )"><option value="" selected="selected"></option><option value="FSD">Sioux Falls, SD</option><option value="SUX">Sioux City, IA</option><option value="HON">Huron, SD</option><option value="MHE">Mitchell, SD</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MPX' )"><option value="" selected="selected"></option><option value="MSP">Minneapolis/St Paul, MN</option><option value="STC">St. Cloud, MN</option><option value="EAU">Eau Claire, WI</option><option value="MPX">Chanhassen, MN</option><option value="RWF">Redwood Falls, MN</option><option value="MKT">Mankato, MN</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','EAX' )"><option value="" selected="selected"></option><option value="MCI">Kansas City, MO</option><option value="STJ">St Joseph, MO</option><option value="MKC">Kansas City Downtown, MO</option><option value="LXT">Lee's Summit, MO</option><option value="IXD">Olathe New Century, KS</option><option value="OJC">Johnson County Exec, KS</option><option value="EAX">Pleasant Hill, MO</option><option value="CDJ">Chillicothe, MO</option><option value="DMO">Sedalia, MO</option><option value="IRK">Kirksville, MO</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','SGF' )"><option value="" selected="selected"></option><option value="SGF">Springfield, MO</option><option value="JLN">Joplin, MO</option><option value="UNO">West Plains, MO</option><option value="VIH">Vichy/Rolla, MO</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','ARX' )"><option value="" selected="selected"></option><option value="RST">Rochester, MN</option><option value="LSE">La Crosse, WI</option><option value="OVS">Boscobel, WI</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','DMX' )"><option value="" selected="selected"></option><option value="DSM">Des Moines, IA</option><option value="ALO">Waterloo, IA</option><option value="MCW">Mason City, IA</option><option value="OTM">Ottumwa, IA</option><option value="MIW">Marshalltown, IA</option><option value="LWD">Lamoni, IA</option><option value="AMW">Ames, IA</option><option value="EST">Estherville, IA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MQT' )"><option value="" selected="selected"></option><option value="MQT">Marquette, MI</option><option value="ANJ">Sault Ste. Marie, MI</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','DLH' )"><option value="" selected="selected"></option><option value="DLH">Duluth, MN</option><option value="INL">International Falls, MN</option><option value="BRD">Brainerd, MN</option><option value="HIB">Hibbing, MN</option><option value="ASX">Ashland, WI</option><option value="MSP">Minneapolis/St Paul</option><option value="MPX">Chanhassen, MN</option><option value="STC">St Cloud, MN</option><option value="FGF">Grand Forks, ND</option><option value="EAU">Eau Claire, WI</option><option value="GRB">Green Bay, WI</option><option value="MQT">Marquette, MI</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','GRB' )"><option value="" selected="selected"></option><option value="GRB">Green Bay, WI</option><option value="MFI">Marshfield, WI</option><option value="OSH">Oshkosh, WI</option><option value="RHI">Rhinelander, WI</option><option value="AUW">Wausau, WI</option><option value="ISW">Wisconsin Rapids, WI</option><option value="DLH">Duluth, MN</option><option value="LSE">La Crosse, WI</option><option value="MSN">Madison, WI</option><option value="MQT">Marquette, MI</option><option value="MKE">Milwaukee, WI</option><option value="MSP">Minneapolis, MN</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','DVN' )"><option value="" selected="selected"></option><option value="BRL">Burlington, IA</option><option value="CID">Cedar Rapids, IA</option><option value="DVN">Davenport, IA</option><option value="DBQ">Dubuque, IA</option><option value="IOW">Iowa City, IA</option><option value="MLI">Moline, IL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','PAH' )"><option value="" selected="selected"></option><option value="PAH">Paducah, KY</option><option value="EVV">Evansville, IN</option><option value="CGI">Cape Girardeau, MO</option><option value="MDH">Carbondale, IL</option><option value="POF">Poplar Bluff, MO</option><option value="OWB">Owensboro, KY</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LSX' )"><option value="" selected="selected"></option><option value="STL">St. Louis, MO</option><option value="COU">Columbia, MO</option><option value="UIN">Quincy, IL</option><option value="JEF">Jefferson City, MO</option><option value="SUS">Chesterfield, MO</option><option value="SET">St. Charles, MO</option><option value="CPS">Cahokia, IL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','ILX' )"><option value="" selected="selected"></option><option value="PIA">Peoria, IL</option><option value="SPI">Springfield, IL</option><option value="BMI">Bloomington, IL</option><option value="CMI">Champaign, IL</option><option value="DEC">Decatur, IL</option><option value="LWV">Lawrenceville, IL</option><option value="ILX">Lincoln, IL</option><option value="MTO">Mattoon, IL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LOT' )"><option value="" selected="selected"></option><option value="ORD">Chicago O'Hare, IL</option><option value="RFD">Rockford, IL</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MKX' )"><option value="" selected="selected"></option><option value="MKE">Milwaukee, WI</option><option value="MSN">Madison, WI</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','APX' )"><option value="" selected="selected"></option><option value="APN">Alpena, MI</option><option value="GLR">Gaylord, MI</option><option value="HTL">Houghton Lake, MI</option><option value="ANJ">Sault Ste. Marie, MI</option><option value="TVC">Traverse City, MI</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','GRR' )"><option value="" selected="selected"></option><option value="GRR">Grand Rapids</option><option value="LAN">Lansing</option><option value="MKG">Muskegon</option><option value="AZO">Kalamazoo</option><option value="BTL">Battle Creek</option><option value="BIV">Holland</option><option value="JXN">Jackson</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','IWX' )"><option value="" selected="selected"></option><option value="FWA">Fort Wayne, IN</option><option value="SBN">South Bend, IN</option><option value="GSH">Goshen, IN</option><option value="IWX">NWS Northern Indiana</option><option value="BEH">Benton Harbor, MI</option><option value="DFI">Defiance, OH</option><option value="AOH">Lima, OH</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','IND' )"><option value="" selected="selected"></option><option value="IND">Indianapolis Intl Ap, IN</option><option value="LAF">Lafayette, IN</option><option value="HUF">Terre Haute, IN</option><option value="MIE">Muncie, IN</option><option value="BMG">Bloomington, IN</option><option value="GEZ">Shelbyville, IN</option><option value="EYE">Indianapolis Eagle Creek, IN</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LMK' )"><option value="" selected="selected"></option><option value="SDF">Louisville International Airport</option><option value="LOU">Louisville Bowman Field</option><option value="LEX">Lexington, KY</option><option value="BWG">Bowling Green, KY</option><option value="FFT">Frankfort, KY</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','DTX' )"><option value="" selected="selected"></option><option value="DTW">Detroit, MI</option><option value="FNT">Flint, MI</option><option value="MBS">Saginaw, MI</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','ILN' )"><option value="" selected="selected"></option><option value="CVG">Cincinnati, OH</option><option value="DAY">Dayton, OH</option><option value="CMH">Columbus, OH</option><option value="LHQ">Lancaster, OH</option><option value="OSU">Ohio State Univ</option><option value="VTA">Newark, OH</option><option value="HAO">Hamilton, OH</option><option value="MGY">Dayton Wright Bros</option><option value="ILN">Wilmington, OH</option><option value="LUK">Cincy Lunken</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','RLX' )"><option value="" selected="selected"></option><option value="BKW">Beckley, WV</option><option value="CRW">Charleston, WV</option><option value="CKB">Clarksburg, WV</option><option value="EKN">Elkins, WV</option><option value="HTS">Huntington, WV</option><option value="PKB">Parkersburg, WV</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','PBZ' )"><option value="" selected="selected"></option><option value="PIT">Pittsburgh, PA</option><option value="MGW">Morgantown, WV</option><option value="ZZV">Zanesville, OH</option><option value="PHD">New Philadelphia, OH</option><option value="HLG">Wheeling, WV</option><option value="DUJ">Dubois, PA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','JKL' )"><option value="" selected="selected"></option><option value="JKL">Jackson, KY</option><option value="LOZ">London, KY</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','CHS' )"><option value="" selected="selected"></option><option value="CHS">North Charleston, SC</option><option value="CXM">Downtown Charleston, SC</option><option value="SAV">Savannah, GA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','CAE' )"><option value="" selected="selected"></option><option value="CAE">Columbia Metro Airport, South Carolina</option><option value="CUB">Columbia Hamilton - Owens Airport, SC</option><option value="OGB">Orangeburg Airport, SC</option><option value="AGS">Augusta Bush Field, GA</option><option value="DNL">Augusta Daniel Field, GA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','GSP' )"><option value="" selected="selected"></option><option value="AND">Anderson, SC</option><option value="AVL">Asheville, NC</option><option value="CLT">Charlotte, NC</option><option value="GSP">Greenville-Spartanburg, SC</option><option value="HKY">Hickory, NC</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MRX' )"><option value="" selected="selected"></option><option value="CHA">Chattanooga, TN</option><option value="TYS">Knoxville, TN</option><option value="TRI">Tri-Cities/Blountville, TN</option><option value="OQT">Oak Ridge, TN</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','RNK' )"><option value="" selected="selected"></option><option value="RNK">Blacksburg, Virginia</option><option value="ROA">Roanoke, Virginia</option><option value="LYH">Lynchburg, Virginia</option><option value="DAN">Danville, Virginia</option><option value="BLF">Bluefield, West Virginia</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','ILM' )"><option value="" selected="selected"></option><option value="ILM">Wilmington, NC</option><option value="FLO">Florence, SC</option><option value="LBT">Lumberton, NC</option><option value="CRE">North Myrtle Beach, SC</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','RAH' )"><option value="" selected="selected"></option><option value="GSO">Greensboro, NC</option><option value="RDU">Raleigh, NC</option><option value="FAY">Fayetteville, NC</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','MHX' )"><option value="" selected="selected"></option><option value="MRH">Beaufort, NC</option><option value="HSE">Cape Hatteras, NC</option><option value="EWN">New Bern, NC</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','AKQ' )"><option value="" selected="selected"></option><option value="RIC">Richmond, VA</option><option value="ORF">Norfolk, VA</option><option value="OFP">Hanover, VA</option><option value="AKQ">Wakefield, VA</option><option value="PHF">Newport News/Patrick Henry Airport, VA</option><option value="WAL">Wallops Island, VA</option><option value="ECG">Elizabeth City, NC</option><option value="SBY">Salisbury, MD</option><option value="OXB">Ocean City, MD</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','LWX' )"><option value="" selected="selected"></option><option value="DCA">Washington-National</option><option value="BWI">Baltimore (BWI)</option><option value="DMH">Baltimore Inner Harbor</option><option value="IAD">Washington-Dulles</option><option value="CHO">Charlottesville</option><option value="MRB">Martinsburg</option><option value="NAK">Annapolis</option><option value="HGR">Hagerstown</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','CLE' )"><option value="" selected="selected"></option><option value="CLE">Cleveland, OH</option><option value="TOL">Toledo, OH</option><option value="MFD">Mansfield, OH</option><option value="CAK">Akron/Canton, OH</option><option value="YNG">Youngstown, OH</option><option value="ERI">Erie, PA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BUF' )"><option value="" selected="selected"></option><option value="BUF">Buffalo, NY</option><option value="ROC">Rochester, NY</option><option value="ART">Watertown, NY</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','CTP' )"><option value="" selected="selected"></option><option value="MDT">Harrisburg, PA</option><option value="IPT">Williamsport, PA</option><option value="AOO">Altoona, PA</option><option value="BFD">Bradford, PA</option><option value="JST">Johnstown, PA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','OKX' )"><option value="" selected="selected"></option><option value="NYC">Central Park NY</option><option value="LGA">LaGuardia Arpt NY</option><option value="JFK">JFK Arpt NY</option><option value="ISP">Islip NY</option><option value="BDR">Bridgeport CT</option><option value="EWR">Newark NJ</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','PHI' )"><option value="" selected="selected"></option><option value="ABE">Allentown, PA</option><option value="ACY">Atlantic City Int'l Airport, NJ</option><option value="55N">Atlantic City Marina, NJ</option><option value="GED">Georgetown, DE</option><option value="PHL">Philadelphia, PA</option><option value="RDG">Reading, PA</option><option value="TTN">Trenton, NJ</option><option value="ILG">Wilmington, DE</option><option value="MPO">Mount Pocono, PA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BGM' )"><option value="" selected="selected"></option><option value="BGM">Binghamton, NY</option><option value="SYR">Syracuse, NY</option><option value="AVP">Scranton/Wilkes-Barre, PA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','ALY' )"><option value="" selected="selected"></option><option value="ALB">Albany, NY</option><option value="GFL">Glens Falls, NY</option><option value="POU">Poughkeepsie, NY</option><option value="DDH">Bennington, VT</option><option value="PSF">Pittsfield, MA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BTV' )"><option value="" selected="selected"></option><option value="BTV">Burlington, VT</option><option value="MPV">Montpelier, VT</option><option value="1V4">St. Johnsbury, VT</option><option value="MVL">Morrisville, VT</option><option value="VSF">Springfield, VT</option><option value="RUT">Rutland, VT</option><option value="PBG">Plattsburgh, NY</option><option value="SLK">Saranac Lake, NY</option><option value="MSS">Massena, NY</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','BOX' )"><option value="" selected="selected"></option><option value="BOS">Boston (Logan Airport), MA</option><option value="BDL">Hartford (Bradley Airport), CT</option><option value="PVD">Providence (T.F. Green Airport), RI</option><option value="ORH">Worcester, MA</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','GYX' )"><option value="" selected="selected"></option><option value="PWM">Portland, ME</option><option value="CON">Concord, NH</option><option value="GYX">Gray, ME</option><option value="MHT">Manchester, NH</option><option value="AUG">Augusta, ME</option></select>
<select size="8" id="availableLocs" style="width:360px;" onchange="push('CF6','CAR' )"><option value="" selected="selected"></option><option value="BGR">Bangor, ME</option><option value="CAR">Caribou, ME</option><option value="HUL">Houlton, ME</option><option value="MLT">Millinocket, ME</option><option value="FVE">Frenchville, ME</option></select>
'''

#Run 3 times with html, html2, html3 respectively
#Written by ChatGPT
soup = BeautifulSoup(html, 'html.parser')
results = []
num = 0
for select in soup.find_all('select'):
    onchange_value = select['onchange']
    acronym_push = onchange_value.split("push('CF6','")[1].split("'")[0]
    options = select.find_all('option')
    for option in options:
        if option['value']:
            acronym_option = option['value']
            name_option = option.text
            results.append([acronym_push, acronym_option, name_option])
    print(num)
    num += 1

with open('cf6_acronyms.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Acronym Push', 'Acronym Option', 'Option Name'])
    for row in results:
        writer.writerow(row)